### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by felixgirault** [HugoGiraudel/react-themed#1]
Hi!

This is not really an issue, but just something I was thinking about while taking a glance at the readme.
Wouldn't it be better to move the config options into the `Themed` function ?

```jsx
import Themed from 'react-themed'

function Button({ theme, ...props }) {
  return (
    <button {...props} className={theme.button}>
      {props.children}
    </button>
  )
}

export Themed(Button, {
  ghost: require('./ghost.css'),
  plain: require('./plain.css'),
  link: require('./link.css')
}, 'plain')
```

That way, the component stays as decoupled as possible, and only knows about the theme passed as a prop.

And to be fully in the functionnal hype, this could also be curried, to integrate easily with librairies like [recompose](https://github.com/acdlite/recompose) : 

```jsx
const themed = Themed({
  ghost: require('./ghost.css'),
  plain: require('./plain.css'),
  link: require('./link.css')
})

export themed(Button)
```

**Comment by HugoGiraudel** [comment]
Funny you ask. This is actually the initial implementation we had with @smartmike and we then moved it to static methods. Not sure what’s best to be entirely honest.

**Comment by felixgirault** [comment]
Oh ok ^^
Not sure either actually, it's just the way I would do it, so I was curious about why you did it this way.
Did you change because of personal taste, or was there a technical reason ?

**Comment by HugoGiraudel** [comment]
Personal taste I think.

**Comment by HugoGiraudel** [comment]
Closing. :)
